export const queryKeys = {
  authBootstrap: ['auth-bootstrap'] as const,
  homeSummary: ['home-summary'] as const,
  statsSummary: ['stats-summary'] as const,
  performanceSummary: ['performance-summary'] as const,
  wallet: ['wallet'] as const,
  stories: ['stories'] as const,
  chapters: ['chapters'] as const,
  storyChapters: (storySlug: string | null | undefined) => ['chapters', storySlug ?? 'all'] as const,
  authoringContent: (kind?: string) => ['authoring-content', kind ?? 'all'] as const,
  authoringContentDetail: (id: number) => ['authoring-content-detail', id] as const,
  authoringChapters: ['authoring-chapters'] as const,
  shopCatalog: ['shop-catalog'] as const,
  preferences: ['player-preferences'] as const,
  chapterOverview: (chapterId: number | null | undefined) => ['chapter-overview', chapterId] as const,
  learnedSkills: ['learned-skills'] as const,
  chapterBook: (chapterId: number | null | undefined) => ['chapter-book', chapterId] as const,
  orientationLessons: (chapterId: number | null | undefined) => ['orientation-lessons', chapterId] as const,
  orientationLesson: (lessonId: number | null | undefined) => ['orientation-lesson', lessonId] as const,
  commandFormPreview: (formId: number) => ['command-form-preview', formId] as const,
  challengeRun: (runId: number) => ['challenge-run', runId] as const,
  adventureRun: (runId: number) => ['adventure-run', runId] as const,
  adventureTierRun: (runId: number) => ['adventure-tier-run', runId] as const,
  adventureLevelLibrary: (runId: number) => ['adventure-level-library', runId] as const,
  adminOverview: ['admin-overview'] as const,
  adminUsers: (query?: string) => ['admin-users', query ?? ''] as const,
  adminUser: (id: number) => ['admin-user', id] as const,
  adminTransactions: (userId?: number) => ['admin-transactions', userId ?? 'all'] as const,
  adminStories: ['admin-stories'] as const,
  adminChapters: (storyId?: number) => ['admin-chapters', storyId ?? 'all'] as const,
  adminContent: ['admin-content'] as const,
  adminAnalytics: ['admin-analytics'] as const,
  adminModeration: ['admin-moderation'] as const,
  adminSettings: ['admin-settings'] as const,
}

export const queryKeyRoots = {
  chapterOverview: ['chapter-overview'] as const,
}
