from django.urls import path

from adventures.views import (
    AdventureLevelRunStartAPIView,
    AdventureLevelTierCommandSubmitAPIView,
    AdventureLevelTierRetryAPIView,
    AdventureLevelTierRunDetailAPIView,
    AdventureLevelTierRunStartAPIView,
    AdventureLevelTierWorkspaceFileAPIView,
    AdventureRunDetailAPIView,
    AdventureRunLevelLibraryAPIView,
    AdventureRunStartAPIView,
    AdventureRunSubmitCommandAPIView,
    AdventureWorkspaceFileAPIView,
)

urlpatterns = [
    path(
        "adventure-levels/<int:level_id>/runs/",
        AdventureLevelRunStartAPIView.as_view(),
        name="adventure-level-run-start",
    ),
    path(
        "adventures/<slug:adventure_slug>/runs/",
        AdventureRunStartAPIView.as_view(),
        name="adventure-run-start",
    ),
    path(
        "adventure-runs/<int:run_id>/",
        AdventureRunDetailAPIView.as_view(),
        name="adventure-run-detail",
    ),
    path(
        "adventure-runs/<int:run_id>/level-library/",
        AdventureRunLevelLibraryAPIView.as_view(),
        name="adventure-run-level-library",
    ),
    path(
        "adventure-runs/<int:run_id>/submit-command/",
        AdventureRunSubmitCommandAPIView.as_view(),
        name="adventure-run-submit-command",
    ),
    path(
        "adventure-runs/<int:run_id>/files/",
        AdventureWorkspaceFileAPIView.as_view(),
        name="adventure-run-files",
    ),
    path(
        "adventure-level-tiers/<int:tier_id>/runs/",
        AdventureLevelTierRunStartAPIView.as_view(),
        name="adventure-level-tier-run-start",
    ),
    path(
        "adventure-tier-runs/<int:run_id>/",
        AdventureLevelTierRunDetailAPIView.as_view(),
        name="adventure-tier-run-detail",
    ),
    path(
        "adventure-tier-runs/<int:run_id>/submit-command/",
        AdventureLevelTierCommandSubmitAPIView.as_view(),
        name="adventure-tier-run-submit-command",
    ),
    path(
        "adventure-tier-runs/<int:run_id>/files/",
        AdventureLevelTierWorkspaceFileAPIView.as_view(),
        name="adventure-tier-run-files",
    ),
    path(
        "adventure-tier-runs/<int:run_id>/retry/",
        AdventureLevelTierRetryAPIView.as_view(),
        name="adventure-tier-run-retry",
    ),
]
