# Generated by Django 5.2.7 on 2026-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetrialvariant',
            name='solution_workspace_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
