# Generated by Django 5.2.7 on 2026-09-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_adventurelevel_description_adventureleveltier_and_more'),
        ('players', '0002_playerpreferences_onboarding_phase'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLevelTierCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('counted_action_total', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='adventures.adventureleveltier')),
                ('tier_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion', to='adventures.adventureleveltierrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'tier'), name='unique_adv_level_tier_completion'), models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='adv_level_tier_completion_stars_lte_3')],
            },
        ),
    ]
