# Generated by Django 5.2.7 on 2026-09-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('players', '0002_playerpreferences_onboarding_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_orientation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChapterOrientationLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('content_html', models.TextField()),
                ('scoped_css', models.TextField(blank=True)),
                ('interaction_steps', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_lessons', to='curriculum.chapter')),
            ],
            options={
                'ordering': ['chapter__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChapterOrientationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('highest_step_seen', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='curriculum.chapterorientationlesson')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_progress', to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chapterorientationlesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_orientation_lesson_chapter_slug'),
        ),
        migrations.AddConstraint(
            model_name='chapterorientationprogress',
            constraint=models.UniqueConstraint(fields=('player', 'lesson'), name='unique_orientation_progress_player_lesson'),
        ),
    ]
