# Generated by Django 5.2.7 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_adventureleveltierprogress_and_more'),
        ('challenges', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commandstep',
            name='command_step_exactly_one_parent',
        ),
        migrations.AddField(
            model_name='commandstep',
            name='adventure_tier_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='adventures.adventureleveltierrun'),
        ),
        migrations.AddIndex(
            model_name='commandstep',
            index=models.Index(fields=['adventure_tier_run', 'id'], name='cmdstep_tier_run_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='commandstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adventure_tier_run__isnull', True), ('attempt__isnull', True), ('challenge_run__isnull', False)), models.Q(('adventure_tier_run__isnull', True), ('attempt__isnull', False), ('challenge_run__isnull', True)), models.Q(('adventure_tier_run__isnull', False), ('attempt__isnull', True), ('challenge_run__isnull', True)), _connector='OR'), name='command_step_exactly_one_parent'),
        ),
    ]
