# Generated by Django 5.2.7 on 2026-09-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_initial'),
        ('curriculum', '0001_initial'),
        ('players', '0002_playerpreferences_onboarding_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurelevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AdventureLevelTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=12)),
                ('is_published', models.BooleanField(default=True)),
                ('adventure_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='adventures.adventurelevel')),
            ],
            options={
                'ordering': ['adventure_level_id', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='AdventureLevelTierWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('story', models.TextField(blank=True)),
                ('task', models.TextField(blank=True)),
                ('min_counted_commands', models.PositiveIntegerField(default=1)),
                ('max_counted_commands', models.PositiveIntegerField(default=4)),
                ('objective_checks', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('command_forms', models.ManyToManyField(blank=True, related_name='adventure_level_tier_waves', to='curriculum.commandform')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='adventures.adventureleveltier')),
            ],
            options={
                'ordering': ['tier_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureLevelTierRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=16)),
                ('is_replay', models.BooleanField(default=False)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('counted_command_count', models.PositiveIntegerField(default=0)),
                ('repository_state', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_tier_runs', to='players.player')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='adventures.adventureleveltier')),
                ('current_wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_runs', to='adventures.adventureleveltierwave')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureLevelTierWaveVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160)),
                ('label', models.CharField(max_length=80)),
                ('initial_state', models.JSONField(default=dict)),
                ('evaluation_spec', models.JSONField(blank=True, default=dict)),
                ('target_state', models.JSONField(blank=True, default=dict)),
                ('solution_commands', models.JSONField(blank=True, default=list)),
                ('case_id', models.CharField(blank=True, max_length=160)),
                ('semantic_key', models.CharField(blank=True, max_length=240)),
                ('parameter_context', models.JSONField(blank=True, default=dict)),
                ('scenario_context', models.JSONField(blank=True, default=dict)),
                ('scaffold_policy', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adventures.adventureleveltierwave')),
            ],
            options={
                'ordering': ['wave_id', 'semantic_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureLevelTierRunWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=16)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('counted_command_count', models.PositiveIntegerField(default=0)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_waves', to='adventures.adventureleveltierrun')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_waves', to='adventures.adventureleveltierwave')),
                ('selected_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_waves', to='adventures.adventureleveltierwavevariant')),
            ],
            options={
                'ordering': ['run_id', 'wave__sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='selected_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='adventures.adventureleveltierwavevariant'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltier',
            constraint=models.UniqueConstraint(fields=('adventure_level', 'difficulty'), name='unique_adv_level_tier_difficulty'),
        ),
        migrations.AddIndex(
            model_name='adventureleveltierwave',
            index=models.Index(fields=['tier', 'sort_order'], name='adv_lvl_tier_wave_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierwave',
            constraint=models.UniqueConstraint(fields=('tier', 'slug'), name='unique_adv_level_tier_wave_slug'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierwave',
            constraint=models.CheckConstraint(condition=models.Q(('min_counted_commands__gte', 0), ('max_counted_commands__gte', models.F('min_counted_commands'))), name='adv_level_tier_wave_valid_command_budget'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierwavevariant',
            constraint=models.UniqueConstraint(fields=('wave', 'slug'), name='unique_adv_level_tier_wave_variant_slug'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierrunwave',
            constraint=models.UniqueConstraint(fields=('run', 'wave'), name='unique_adv_level_tier_run_wave'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierrunwave',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='adv_level_tier_run_wave_stars_lte_3'),
        ),
        migrations.AddIndex(
            model_name='adventureleveltierrun',
            index=models.Index(fields=['player', 'tier', 'status'], name='advtier_run_plyr_tier_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='adventureleveltierrun',
            index=models.Index(fields=['player', 'status'], name='advtier_run_plyr_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('player', 'tier'), name='unique_active_adv_level_tier_run'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierrun',
            constraint=models.CheckConstraint(condition=models.Q(('stars__lte', 3)), name='adv_level_tier_run_stars_lte_3'),
        ),
    ]
