# Generated by Django 5.2.7 on 2026-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_adventurelevel_description_adventureleveltier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='successful_clears',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureleveltierwave',
            name='required_successful_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
