# Generated by Django 5.2.7 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_adventureleveltierrun_successful_clears_and_more'),
        ('players', '0002_playerpreferences_onboarding_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureLevelTierProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful_clears', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adventureleveltierrun',
            name='command_count',
        ),
        migrations.RemoveField(
            model_name='adventureleveltierrun',
            name='counted_command_count',
        ),
        migrations.RemoveField(
            model_name='adventureleveltierrun',
            name='successful_clears',
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='counted_action_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='max_counted_commands',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='min_counted_commands',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='non_counted_diagnostic_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='prior_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='adventures.adventureleveltierrun'),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='retry_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='source_entry_point',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventureleveltierrun',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='adventures.adventureleveltier'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierrun',
            constraint=models.CheckConstraint(condition=models.Q(('min_counted_commands__gte', 1), ('max_counted_commands__gte', models.F('min_counted_commands'))), name='adv_level_tier_run_valid_command_budget'),
        ),
        migrations.AddField(
            model_name='adventureleveltierprogress',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_tier_progress', to='players.player'),
        ),
        migrations.AddField(
            model_name='adventureleveltierprogress',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='adventures.adventureleveltier'),
        ),
        migrations.AddConstraint(
            model_name='adventureleveltierprogress',
            constraint=models.UniqueConstraint(fields=('player', 'tier'), name='unique_adv_level_tier_progress_player_tier'),
        ),
    ]
