# Generated by Django 5.2.7 on 2026-09-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_adventureleveltierprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureleveltierprogress',
            name='last_shown_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='adventures.adventureleveltierwavevariant'),
        ),
    ]
