# Generated by Django 5.2.7 on 2026-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_adventureleveltierprogress_last_shown_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureleveltierwavevariant',
            name='solution_workspace_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adventurewavevariant',
            name='solution_workspace_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
