# Generated by Django 5.2.7 on 2026-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_adventureleveltierwavevariant_solution_workspace_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureleveltierrun',
            name='changed_variant',
            field=models.BooleanField(default=False),
        ),
    ]
